version: '2'

services:
  <%= serviceName %>:<% if (environment === 'debug') { %>
    image: <%= imageName %>:debug<% } else { %>
    image: <%= imageName %><% } %><% if (isWebProject && portNumber) { %>
    ports:
      - "<%= portNumber %>:<%= portNumber %>"<% } %><% if (environment === 'debug') { %><% if (volumeMap !== null) { %>
    volumes:
      - <%= volumeMap %><% } %><% if (projectType === 'aspnet') { %>
    environment:
      - REMOTE_DEBUGGING<% } %><% } %>
    labels:
      com.<%= imageName %>.environment: "<%= environment %>"
